DROP TABLE If EXISTS "users" CASCADE;

DROP TABLE If EXISTS "flats" CASCADE;

DROP TABLE If EXISTS "groups" CASCADE;

DROP TABLE If EXISTS "items" CASCADE;

DROP TABLE If EXISTS "user_flats" CASCADE;

DROP TABLE If EXISTS "flat_groups" CASCADE;
